// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mcejzxisdjoiddiokyvy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jZWp6eGlzZGpvaWRkaW9reXZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2NTE1MTcsImV4cCI6MjA2MjIyNzUxN30.qEg30Jk6NeRpmSl4wvMSNYYHqtm0Xya1ZBEam0_yM74";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});