// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bzchtpmzcbohrveykftz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6Y2h0cG16Y2JvaHJ2ZXlrZnR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0NDg2NzEsImV4cCI6MjA2MTAyNDY3MX0.RpC9xwF0Im8gvkU9K3toWN2Hl9btl1YM0XX9itgnmRc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});